linkhome: "https://rubyonrails.org/"
linknew: "http://news.railstutorial.org"
linkauthor: "http://www.michaelhartl.com/"
<<<<<<< HEAD
maxlength: 225
=======
>>>>>>> 6075bef... Chapter 5: Filling the layout
